version: "3.9"

services:
  postgres:
    image: postgres
    hostname: baka.postgres
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "secret"
    ports:
      - "5432:5432"
  identity:
    container_name: identity
    hostname: baka.identity
    restart: on-failure
    ports:
      - 8888:80
      - 8889:443
    build:      
      context: .
      dockerfile: services/identity/Dockerfile
    depends_on: 
      - postgres 
  