version: "3.9"

services:
  postgres:
    image: postgres
    hostname: baka.postgres
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "secret"
    ports:
      - "5432:5432"
  web-client:
    container_name: web-clinet
    hostname: baka.client
    restart: unless-stopped:5
    ports:
      - 8000:80
      - 8001:443
    build:
      context: clients/spa-client
      dockerfile: Dockerfile
  identity:
    container_name: identity
    hostname: baka.identity
    restart: unless-stopped:5
    ports:
      - 8888:80
      - 8889:443
    build:      
      context: .
      dockerfile: services/identity/Dockerfile
    depends_on: 
      - postgres
  